services:
  db:
    container_name: missive_db
    image: postgres:16.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data"

  api:
    container_name: missive_api
    build: ./missive_api
    restart: always
    env_file: ./missive_api/.env
    volumes:
      - ./missive_api:/app
    ports:
      - "4001:4000"
    depends_on:
      - db

  web:
    container_name: missive_client
    build: ./missive_client
    volumes:
      - ./missive_client:/app
    ports:
      - "4000:4000"
    depends_on:
      - api

volumes:
  pgdata: